image: continuumio/anaconda3:2022.05
stages:
  - check-files
  - lint
  - run

check-lab-files:
  tags:
    - docker
  stage: check-files
  script:
    - test -f .gitignore
    - test -f .pylintrc
    - test -f common/describe_data.py
    - test -f common/test_env.py
    - test -f lab4.py
    - test -f README.md || test -f Readme.markdown
    - test -d data
    - test -d results
    - find . -name "*" -not -path "./.git/*" -not -path "./builds/*" 2>&1

lint-lab:
  tags:
    - docker
  stage: lint
  script:
    # Check formatting
    # autopep8 ignore=C2801
    # --exit-code
    - autopep8 --ignore=C2801,I0021 --exit-code -d lab4.py common/*.py
    # Lint
    # Upgrade pylint to latest to have same latest version in local development environment and in CI
    - pip install pylint --upgrade
    # pylint: disable=C2801, I0021
    - pylint --disable=C2801,I0021 lab4.py common/*.py

run-lab:
  tags:
    - docker
  stage: run
  script:
    - chmod +x lab4.py
    - ./lab4.py
  artifacts:
    name: lab4-results-$CI_COMMIT_SHORT_SHA
    paths:
      - results/
